/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.ManageHalls;

import Services.ExceptionMessageDialog;
import Services.ManageOperations.ManageFacilities;
import Services.ManageOperations.ManageHalls;
import Services.ManageOperations.ManageHallsHasFacilities;
import Services.TableModelBuilder;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author janith
 */
public class AddHallsView extends javax.swing.JPanel {

    /**
     * Creates new form AddHallsView
     */
    public AddHallsView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        facilitesTable = new javax.swing.JTable();
        hallNameTxt = new javax.swing.JTextField();
        capacitySpnr = new javax.swing.JSpinner();
        priceSpnr = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        facilitesTable.setModel(getFacilitiesTableModel());
        jScrollPane1.setViewportView(facilitesTable);

        capacitySpnr.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        priceSpnr.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.0d), Double.valueOf(0.0d), null, Double.valueOf(1.0d)));

        jLabel1.setText("Add new Hall");

        jLabel2.setText("Hall Name");

        jLabel3.setText("Capacity");

        jLabel4.setText("Price");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(hallNameTxt)
                            .addComponent(capacitySpnr, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                            .addComponent(priceSpnr))))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(hallNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(capacitySpnr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(priceSpnr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private TableModel getFacilitiesTableModel() {
        try {
            ManageFacilities mf = new ManageFacilities();
            DefaultTableModel baseModel =  (DefaultTableModel) TableModelBuilder.build(mf.read("ALL"));
            Vector v = new Vector();
            for (int i = 0; i < baseModel.getRowCount(); i++) {
                v.add(0);
            }
            baseModel.addColumn("Count", v);
            return baseModel;
        } catch (SQLException ex) {
            ex.printStackTrace();
            ExceptionMessageDialog.show(this, ex.getLocalizedMessage());
            return null;
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner capacitySpnr;
    private javax.swing.JTable facilitesTable;
    private javax.swing.JTextField hallNameTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner priceSpnr;
    // End of variables declaration//GEN-END:variables

    public void createHall() {
        //method to be called after the joption pane ok option is pressed
        String hallName = hallNameTxt.getText();
        int capacity = (int) capacitySpnr.getValue();
        double price = (double) priceSpnr.getValue();
        Object values[] = {hallName, capacity, price};
        ManageHalls mh = new ManageHalls();
        mh.create(values, mh.columnNames);
        int lastInsertID = mh.getLastInsertID();
        ManageHallsHasFacilities mhf = new ManageHallsHasFacilities();
        for (int i = 0; i < facilitesTable.getRowCount(); i++) {
            if(!facilitesTable.getValueAt(i, 2).toString().equals("0")){
                String[] temp  = {lastInsertID+"",facilitesTable.getValueAt(i,0 ).toString(),facilitesTable.getValueAt(i, 1).toString(),facilitesTable.getValueAt(i, 2).toString()};
                mhf.create(temp, mhf.columnNames);
                System.out.println(facilitesTable.getValueAt(i, 1).toString()+"_"+facilitesTable.getValueAt(i, 2).toString());
            }
        }

        //
        //this.setVisible(false);
    }
}
