/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.ManageBookings;

import Services.ExceptionMessageDialog;
import Services.ManageOperations.ManageBookings;
import Services.ManageOperations.ManageHalls;
import Views.ManageHalls.SearchHallsView;
import Views.ManageHalls.SelectHallTableView;
import com.github.lgooddatepicker.optionalusertools.DateChangeListener;
import com.github.lgooddatepicker.zinternaltools.DateChangeEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author janith
 */
public class UpdateBookingsView extends javax.swing.JPanel {

    /**
     * Creates new form UpdateBookingsView
     */
    public UpdateBookingsView() {
        initComponents();
    }

    private ManageHalls mh = new ManageHalls();
    private ManageBookings mb = new ManageBookings();
    private int hallId = -1;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TuesdayChk = new javax.swing.JCheckBox();
        WednesdayChk = new javax.swing.JCheckBox();
        FridayChk = new javax.swing.JCheckBox();
        SaturdayChk = new javax.swing.JCheckBox();
        SundayChk = new javax.swing.JCheckBox();
        ThursdayChk = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        confirmedChk = new javax.swing.JCheckBox();
        searchHalls = new javax.swing.JButton();
        hallSearchResultLabel = new javax.swing.JLabel();
        startDatePicker = new com.github.lgooddatepicker.components.DatePicker();
        endDatePicker = new com.github.lgooddatepicker.components.DatePicker();
        jLabel7 = new javax.swing.JLabel();
        bookedByTxt = new javax.swing.JTextField();
        hallSelectedChk = new javax.swing.JCheckBox();
        bookedBySelectedChk = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        startDateSelectedChk = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        endDateSelectedChk = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        dowSelectedChk = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jCheckBox6 = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        MondayChk = new javax.swing.JCheckBox();

        TuesdayChk.setText("Tuesday");
        TuesdayChk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TuesdayChkDayOfWeekChkActionPerformed(evt);
            }
        });

        WednesdayChk.setText("Wednesday");
        WednesdayChk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WednesdayChkDayOfWeekChkActionPerformed(evt);
            }
        });

        FridayChk.setText("Friday");
        FridayChk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FridayChkDayOfWeekChkActionPerformed(evt);
            }
        });

        SaturdayChk.setText("Saturday");
        SaturdayChk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaturdayChkDayOfWeekChkActionPerformed(evt);
            }
        });

        SundayChk.setText("Sunday");
        SundayChk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SundayChkDayOfWeekChkActionPerformed(evt);
            }
        });

        ThursdayChk.setText("Thursday");
        ThursdayChk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThursdayChkDayOfWeekChkActionPerformed(evt);
            }
        });

        jLabel6.setText("Confirmed");

        confirmedChk.setText("Confirm");
        confirmedChk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmedChkActionPerformed(evt);
            }
        });

        searchHalls.setText("Search Halls");
        searchHalls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchHallsActionPerformed(evt);
            }
        });

        hallSearchResultLabel.setText(" ");

        startDatePicker.setText("Pick Start Date");
        startDatePicker.addDateChangeListener(new DateChangeListenerChk("START"));

        endDatePicker.setText("Pick End Date");
        endDatePicker.addDateChangeListener(new DateChangeListenerChk("END"));

        jLabel7.setText("Booked By");

        bookedByTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                bookedByTxtKeyReleased(evt);
            }
        });

        hallSelectedChk.setEnabled(false);

        bookedBySelectedChk.setEnabled(false);

        jLabel1.setText("Search Halls");

        startDateSelectedChk.setEnabled(false);

        jLabel2.setText("Currently Selected");

        endDateSelectedChk.setEnabled(false);

        jLabel3.setText("Start Date");

        dowSelectedChk.setEnabled(false);

        jLabel4.setText("End Date");

        jCheckBox6.setEnabled(false);

        jLabel5.setText("Day of week");

        jCheckBox1.setText("All day");

        MondayChk.setText("Monday");
        MondayChk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MondayChkDayOfWeekChkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCheckBox6)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(confirmedChk)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(hallSelectedChk)
                            .addComponent(bookedBySelectedChk)
                            .addComponent(startDateSelectedChk)
                            .addComponent(endDateSelectedChk)
                            .addComponent(dowSelectedChk))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7))
                                .addGap(86, 86, 86)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(endDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(startDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bookedByTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(162, 162, 162))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(hallSearchResultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(187, 187, 187))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(searchHalls)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(WednesdayChk)
                                                            .addComponent(MondayChk, javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(TuesdayChk, javax.swing.GroupLayout.Alignment.LEADING))
                                                        .addGap(18, 18, 18)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(FridayChk)
                                                            .addComponent(ThursdayChk)
                                                            .addComponent(SaturdayChk)))
                                                    .addComponent(jCheckBox1))
                                                .addGap(18, 18, 18)
                                                .addComponent(SundayChk)))
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(searchHalls)
                    .addComponent(hallSelectedChk))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(hallSearchResultLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(bookedByTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bookedBySelectedChk))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(startDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(startDateSelectedChk))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(endDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(endDateSelectedChk))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(dowSelectedChk))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MondayChk)
                            .addComponent(ThursdayChk)
                            .addComponent(SundayChk))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FridayChk, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TuesdayChk))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(WednesdayChk)
                            .addComponent(SaturdayChk))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox1)
                        .addGap(12, 12, 12)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(confirmedChk))
                    .addComponent(jCheckBox6))
                .addGap(109, 109, 109))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TuesdayChkDayOfWeekChkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TuesdayChkDayOfWeekChkActionPerformed
        // TODO add your handling code here:
        dowSelectedChk.setSelected(
            MondayChk.isSelected() || TuesdayChk.isSelected() || WednesdayChk.isSelected() ||
            ThursdayChk.isSelected() || FridayChk.isSelected() || SaturdayChk.isSelected() ||
            SundayChk.isSelected()
        );
    }//GEN-LAST:event_TuesdayChkDayOfWeekChkActionPerformed

    private void WednesdayChkDayOfWeekChkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WednesdayChkDayOfWeekChkActionPerformed
        // TODO add your handling code here:
        dowSelectedChk.setSelected(
            MondayChk.isSelected() || TuesdayChk.isSelected() || WednesdayChk.isSelected() ||
            ThursdayChk.isSelected() || FridayChk.isSelected() || SaturdayChk.isSelected() ||
            SundayChk.isSelected()
        );
    }//GEN-LAST:event_WednesdayChkDayOfWeekChkActionPerformed

    private void FridayChkDayOfWeekChkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FridayChkDayOfWeekChkActionPerformed
        // TODO add your handling code here:
        dowSelectedChk.setSelected(
            MondayChk.isSelected() || TuesdayChk.isSelected() || WednesdayChk.isSelected() ||
            ThursdayChk.isSelected() || FridayChk.isSelected() || SaturdayChk.isSelected() ||
            SundayChk.isSelected()
        );
    }//GEN-LAST:event_FridayChkDayOfWeekChkActionPerformed

    private void SaturdayChkDayOfWeekChkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaturdayChkDayOfWeekChkActionPerformed
        // TODO add your handling code here:
        dowSelectedChk.setSelected(
            MondayChk.isSelected() || TuesdayChk.isSelected() || WednesdayChk.isSelected() ||
            ThursdayChk.isSelected() || FridayChk.isSelected() || SaturdayChk.isSelected() ||
            SundayChk.isSelected()
        );
    }//GEN-LAST:event_SaturdayChkDayOfWeekChkActionPerformed

    private void SundayChkDayOfWeekChkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SundayChkDayOfWeekChkActionPerformed
        // TODO add your handling code here:
        dowSelectedChk.setSelected(
            MondayChk.isSelected() || TuesdayChk.isSelected() || WednesdayChk.isSelected() ||
            ThursdayChk.isSelected() || FridayChk.isSelected() || SaturdayChk.isSelected() ||
            SundayChk.isSelected()
        );
    }//GEN-LAST:event_SundayChkDayOfWeekChkActionPerformed

    private void ThursdayChkDayOfWeekChkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThursdayChkDayOfWeekChkActionPerformed
        // TODO add your handling code here:
        dowSelectedChk.setSelected(
            MondayChk.isSelected() || TuesdayChk.isSelected() || WednesdayChk.isSelected() ||
            ThursdayChk.isSelected() || FridayChk.isSelected() || SaturdayChk.isSelected() ||
            SundayChk.isSelected()
        );
    }//GEN-LAST:event_ThursdayChkDayOfWeekChkActionPerformed

    private void confirmedChkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmedChkActionPerformed
        // TODO add your handling code here:
        confirmedChk.setSelected(true);
    }//GEN-LAST:event_confirmedChkActionPerformed

    private void searchHallsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchHallsActionPerformed
        // TODO add your handling code here:
        //search for halls
        try {
            SearchHallsView shv = new SearchHallsView();
            int firstResult = JOptionPane.showConfirmDialog(this, shv, "Search halls", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
            if (firstResult == JOptionPane.OK_OPTION) {
                ResultSet searchResultSet = shv.searchHalls();
                SelectHallTableView shtv = new SelectHallTableView(searchResultSet);
                int secondResult = JOptionPane.showConfirmDialog(this, shtv, "Select Halls", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
                if (secondResult == JOptionPane.OK_OPTION && shtv.getSelectedHall() != -1) {

                    int hallid = shtv.getSelectedHall();
                    this.hallId = hallid;
                    ResultSet hallResult = mh.read("hallid = " + hallid);
                    String hallString = "";
                    while (hallResult.next()) {
                        hallString = "Name: " + hallResult.getString("name");
                        hallString += " Capacity: " + hallResult.getString("capacity");
                        hallString += " Price: " + hallResult.getString("price");
                    }
                    hallSearchResultLabel.setText(hallString);
                    hallSelectedChk.setSelected(true);
                }else{
                    JOptionPane.showMessageDialog(this, "No Hall Selected");
                }
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
            ExceptionMessageDialog.show(this, ex.getLocalizedMessage());
        }
    }//GEN-LAST:event_searchHallsActionPerformed

    private void bookedByTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bookedByTxtKeyReleased
        // TODO add your handling code here:
        bookedBySelectedChk.setSelected(!bookedByTxt.getText().equals(""));
    }//GEN-LAST:event_bookedByTxtKeyReleased

    private void MondayChkDayOfWeekChkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MondayChkDayOfWeekChkActionPerformed
        // TODO add your handling code here:
        dowSelectedChk.setSelected(
            MondayChk.isSelected() || TuesdayChk.isSelected() || WednesdayChk.isSelected() ||
            ThursdayChk.isSelected() || FridayChk.isSelected() || SaturdayChk.isSelected() ||
            SundayChk.isSelected()
        );
    }//GEN-LAST:event_MondayChkDayOfWeekChkActionPerformed

    private class DateChangeListenerChk implements DateChangeListener {

        private String tag;
        public DateChangeListenerChk(String tag) {
            this.tag = tag;
        }

        @Override
        public void dateChanged(DateChangeEvent dce) {
            if(this.tag.equals("START")){
                if(dce.getNewDate().toString().equals("")){
                    UpdateBookingsView.this.startDateSelectedChk.setSelected(false);
                }else{
                    UpdateBookingsView.this.startDateSelectedChk.setSelected(true);
                }
            }else if(this.tag.equals("END")){
                if(dce.getNewDate().toString().equals("")){
                    UpdateBookingsView.this.endDateSelectedChk.setSelected(false);
                }else{
                    UpdateBookingsView.this.endDateSelectedChk.setSelected(false);
                }
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox FridayChk;
    private javax.swing.JCheckBox MondayChk;
    private javax.swing.JCheckBox SaturdayChk;
    private javax.swing.JCheckBox SundayChk;
    private javax.swing.JCheckBox ThursdayChk;
    private javax.swing.JCheckBox TuesdayChk;
    private javax.swing.JCheckBox WednesdayChk;
    private javax.swing.JCheckBox bookedBySelectedChk;
    private javax.swing.JTextField bookedByTxt;
    private javax.swing.JCheckBox confirmedChk;
    private javax.swing.JCheckBox dowSelectedChk;
    private com.github.lgooddatepicker.components.DatePicker endDatePicker;
    private javax.swing.JCheckBox endDateSelectedChk;
    private javax.swing.JLabel hallSearchResultLabel;
    private javax.swing.JCheckBox hallSelectedChk;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton searchHalls;
    private com.github.lgooddatepicker.components.DatePicker startDatePicker;
    private javax.swing.JCheckBox startDateSelectedChk;
    // End of variables declaration//GEN-END:variables
}
